version: 2.1
orbs:
  snyk: snyk/snyk@1.7.0

jobs: # a collection of steps

  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/java-goof/todolist-goof # directory where steps will run
    docker: # run the steps with Docker
      - image: cimg/openjdk:11.0 # ...with this image as the primary container; this is where all `steps` will run
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: Maven Build
          command: 'mvn install' 
      - snyk/scan:
          token-variable: SNYK
          monitor-on-build: true
          fail-on-issues: false
          organization: devops-group  
          additional-arguments: --all-projects --target-reference=main --remote-repo-url=full-monorepo
